# Generated by Django 5.1.3 on 2026-09-19 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_tarifa', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('id_actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.PROTECT, to='simulactores.actor')),
            ],
            options={
                'db_table': 'asignacion',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='simulactores.actor')),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id_escenario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='simulactores.categoria')),
            ],
            options={
                'db_table': 'escenario',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('id_asignacion', models.ForeignKey(db_column='id_asignacion', on_delete=django.db.models.deletion.PROTECT, to='simulactores.asignacion')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_interpretes', models.IntegerField(default=1)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_escenario', models.ForeignKey(blank=True, db_column='id_escenario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulactores.escenario')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_solicitud',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='simulactores.solicitud'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='simulactores.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='simulactores.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='simulactores.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='simulactores.usuario')),
            ],
            options={
                'db_table': 'historial_acceso',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=150)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='simulactores.usuario')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='simulactores.usuario'),
        ),
    ]
