# Generated by Django 5.1.3 on 2026-09-26 02:19

import django.db.models.deletion
import simulactores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de confirmación'), ('Activo', 'Activo'), ('Desactivado', 'Desactivado')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='simulactores.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', simulactores.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_tarifa', models.CharField(blank=True, choices=[('Por Hora', 'Por Hora'), ('Por Evento', 'Por Evento')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('habilidades', models.ManyToManyField(blank=True, related_name='actores', to='simulactores.habilidad')),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=150)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_bloque', models.CharField(choices=[('Disponible', 'Disponible'), ('Bloqueado', 'Bloqueado')], default='Disponible', max_length=20)),
                ('actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='simulactores.actor')),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id_escenario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('guion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Examen ECOE', 'Examen ECOE (Evaluación Clínica Objetiva Estructurada)'), ('Manejo de Crisis', 'Manejo de Crisis (CRM)'), ('Comunicación SPIKES', 'Comunicación SPIKES'), ('Seguridad del Paciente', 'Seguridad del Paciente'), ('Simulación Corporativa', 'Simulación Corporativa'), ('Otro', 'Otro')], default='Otro', max_length=30)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Archivado', 'Archivado')], default='Activo', max_length=20)),
                ('categorias', models.ManyToManyField(blank=True, related_name='escenarios', to='simulactores.categoria')),
            ],
            options={
                'db_table': 'escenario',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('correo_intento', models.EmailField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('Exitoso', 'Exitoso'), ('Fallido', 'Fallido')], max_length=20)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_acceso',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('numero_solicitud', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_simulacion', models.CharField(choices=[('Examen ECOE', 'Examen ECOE (Evaluación Clínica Objetiva Estructurada)'), ('Manejo de Crisis', 'Manejo de Crisis (CRM)'), ('Comunicación SPIKES', 'Comunicación SPIKES'), ('Seguridad del Paciente', 'Seguridad del Paciente'), ('Simulación Corporativa', 'Simulación Corporativa'), ('Otro', 'Otro')], max_length=30)),
                ('cantidad_interpretes', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Revisión', 'En Revisión'), ('Aprobada', 'Aprobada'), ('Actor Asignado', 'Actor Asignado'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('escenario', models.ForeignKey(blank=True, db_column='id_escenario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='simulactores.escenario')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de confirmación'), ('Confirmada', 'Confirmada'), ('Rechazada', 'Rechazada'), ('Ejecutada', 'Ejecutada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('hora_inicio_real', models.TimeField(blank=True, null=True)),
                ('hora_fin_real', models.TimeField(blank=True, null=True)),
                ('tarifa_aplicada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='simulactores.actor')),
                ('solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='simulactores.solicitud')),
            ],
            options={
                'db_table': 'asignacion',
            },
        ),
        migrations.CreateModel(
            name='TarifaActor',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_tarifa', models.CharField(choices=[('Por Hora', 'Por Hora'), ('Por Evento', 'Por Evento')], max_length=20)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tarifas', to='simulactores.actor')),
            ],
            options={
                'db_table': 'tarifa_actor',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('SINPE Móvil', 'SINPE Móvil'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='simulactores.actor')),
                ('asignaciones', models.ManyToManyField(blank=True, help_text='Asignaciones ejecutadas cubiertas por este pago mensual.', related_name='pagos', to='simulactores.asignacion')),
            ],
            options={
                'db_table': 'pago',
                'unique_together': {('actor', 'periodo_mes', 'periodo_anio')},
            },
        ),
    ]
